const fs = require('fs');
const path = require('path');
const { Sequelize } = require('sequelize');
require('dotenv').config({ path: path.join(__dirname, '../.env') });

async function exportSql() {
    console.log('--- Starting SQL Export ---');

    // Connect using existing config
    const sequelize = new Sequelize(process.env.DATABASE_URL, {
        dialect: 'mysql',
        logging: false
    });

    try {
        await sequelize.authenticate();
        console.log('✅ Connected to DB');

        const tables = [
            'Staffs', 'Items', 'Containers', 'ContainerItems',
            'Sales', 'SaleAllocations', 'Firms', 'ScrapTypes',
            'AuditLogs', 'ItemRateHistories', 'Attendances'
        ];

        let sqlContent = `-- SQL Dump generated by Node.js Script\n-- Date: ${new Date().toISOString()}\n\n`;
        sqlContent += `SET FOREIGN_KEY_CHECKS = 0;\n\n`;

        for (const table of tables) {
            console.log(`Exporting table: ${table}...`);

            // Get Table Limits (Schema?) - For now just data.
            // Ideally we want CREATE TABLE too, but Sequelize Sync usually handles that.
            // Users want "DATA script". So INSERTS are most important.

            const [rows] = await sequelize.query(`SELECT * FROM ${table}`);

            if (rows.length > 0) {
                sqlContent += `-- Data for table ${table}\n`;

                rows.forEach(row => {
                    const keys = Object.keys(row).map(k => `\`${k}\``).join(', ');
                    const values = Object.values(row).map(v => {
                        if (v === null) return 'NULL';
                        if (typeof v === 'string') return `'${v.replace(/'/g, "\\'")}'`; // Escape single quotes? 
                        // Basic escape: double up single quotes standard SQL? 
                        // Or backslash? MySQL uses backslash by default.
                        if (v instanceof Date) return `'${v.toISOString().slice(0, 19).replace('T', ' ')}'`;
                        return v;
                    }).join(', ');

                    sqlContent += `INSERT INTO \`${table}\` (${keys}) VALUES (${values});\n`;
                });
                sqlContent += `\n`;
            }
        }

        sqlContent += `SET FOREIGN_KEY_CHECKS = 1;\n`;

        fs.writeFileSync(path.join(__dirname, '../../scrap_system_backup.sql'), sqlContent);
        console.log('✅ Backup saved to: scrap_system_backup.sql');

    } catch (err) {
        console.error('Export Failed:', err);
    } finally {
        await sequelize.close();
    }
}

exportSql();
